"""add_is_testnet_to_exchange_connection

Revision ID: f48e5002e1fc
Revises: 
Create Date: 2026-01-02 22:26:09.505838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f48e5002e1fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('exchange_connections', sa.Column('is_testnet', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE exchange_connections SET is_testnet = FALSE WHERE is_testnet IS NULL")
    # Now make it NOT NULL
    op.alter_column('exchange_connections', 'is_testnet', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_connections', 'is_testnet')
    # ### end Alembic commands ###
